version: '3.7'

services:
  db:
    image: postgres:11.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mobile_game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    build: '.'
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - db
