const ROLES = {
    UNCONFIRMED_TRANSPORTER: 'unconfirmed_transporter',
    UNCONFIRMED_HOLDER: 'unconfirmed_holder',
    UNCONFIRMED_FORWARDER: 'unconfirmed_forwarder',

    CONFIRMED_EMAIL_TRANSPORTER: 'confirmed_email_transporter',
    CONFIRMED_EMAIL_HOLDER: 'confirmed_email_holder',
    CONFIRMED_EMAIL_FORWARDER: 'confirmed_email_forwarder',

    CONFIRMED_EMAIL_AND_PHONE_TRANSPORTER: 'confirmed_email_and_phone_transporter',
    CONFIRMED_EMAIL_AND_PHONE_HOLDER: 'confirmed_email_and_phone_holder',
    CONFIRMED_EMAIL_AND_PHONE_FORWARDER: 'confirmed_email_and_phone_forwarder',

    TRANSPORTER: 'transporter',
    HOLDER: 'holder',
    FORWARDER: 'forwarder',
};

const MAP_FROM_UNCONFIRMED_TO_CONFIRMED_EMAIL_ROLE = {
    [ROLES.UNCONFIRMED_TRANSPORTER]: ROLES.CONFIRMED_EMAIL_TRANSPORTER,
    [ROLES.UNCONFIRMED_HOLDER]: ROLES.CONFIRMED_EMAIL_HOLDER,
    [ROLES.UNCONFIRMED_FORWARDER]: ROLES.CONFIRMED_EMAIL_FORWARDER,
};

const MAP_FROM_PENDING_ROLE_TO_MAIN = {
    [ROLES.CONFIRMED_EMAIL_AND_PHONE_TRANSPORTER]: ROLES.TRANSPORTER,
    [ROLES.CONFIRMED_EMAIL_AND_PHONE_HOLDER]: ROLES.HOLDER,
    [ROLES.CONFIRMED_EMAIL_AND_PHONE_FORWARDER]: ROLES.FORWARDER,
};

const MAP_FROM_CONFIRMED_EMAIL_TO_CONFIRMED_PHONE = {
    [ROLES.CONFIRMED_EMAIL_TRANSPORTER]: ROLES.CONFIRMED_EMAIL_AND_PHONE_TRANSPORTER,
    [ROLES.CONFIRMED_EMAIL_HOLDER]: ROLES.CONFIRMED_EMAIL_AND_PHONE_HOLDER,
    [ROLES.CONFIRMED_EMAIL_FORWARDER]: ROLES.CONFIRMED_EMAIL_AND_PHONE_FORWARDER,
};

const UNCONFIRMED_EMAIL_ROLES = [
    ROLES.UNCONFIRMED_TRANSPORTER,
    ROLES.UNCONFIRMED_HOLDER,
    ROLES.UNCONFIRMED_FORWARDER,
];

const ROLES_TO_REGISTER = [
    ROLES.TRANSPORTER, ROLES.HOLDER, ROLES.FORWARDER,
];

const MAP_ROLES_FROM_CLIENT_TO_SERVER = {
    [ROLES.TRANSPORTER]: ROLES.UNCONFIRMED_TRANSPORTER,
    [ROLES.HOLDER]: ROLES.UNCONFIRMED_HOLDER,
    [ROLES.FORWARDER]: ROLES.UNCONFIRMED_FORWARDER,
};

const PERMISSIONS = {
    AUTHORIZATION: 'authorization',
    FINISH_REGISTRATION: 'finish_registration',
    RESET_PASSWORD: 'reset_password',
    CONFIRM_EMAIL: 'confirm_email',
    CONFIRM_PHONE_NUMBER: 'confirm_phone_number',
    REGISTRATION_SAVE_STEP_1: 'registration_save_step_1',
    REGISTRATION_SAVE_STEP_2: 'registration_save_step_2',
    REGISTRATION_SAVE_STEP_3: 'registration_save_step_3',
    REGISTRATION_SAVE_STEP_4: 'registration_save_step_4',
    REGISTRATION_SAVE_STEP_5: 'registration_save_step_5',
};

const ROLES_WITH_PERMISSIONS = [
    [ROLES.UNCONFIRMED_TRANSPORTER, [
        PERMISSIONS.CONFIRM_EMAIL,
    ]],
    [ROLES.UNCONFIRMED_HOLDER, [
        PERMISSIONS.CONFIRM_EMAIL,
    ]],
    [ROLES.UNCONFIRMED_FORWARDER, [
        PERMISSIONS.CONFIRM_EMAIL,
    ]],

    [ROLES.CONFIRMED_EMAIL_TRANSPORTER, [
        PERMISSIONS.AUTHORIZATION,
        PERMISSIONS.RESET_PASSWORD,
        PERMISSIONS.CONFIRM_PHONE_NUMBER,
    ]],
    [ROLES.CONFIRMED_EMAIL_HOLDER, [
        PERMISSIONS.AUTHORIZATION,
        PERMISSIONS.RESET_PASSWORD,
        PERMISSIONS.CONFIRM_PHONE_NUMBER,
    ]],
    [ROLES.CONFIRMED_EMAIL_FORWARDER, [
        PERMISSIONS.AUTHORIZATION,
        PERMISSIONS.RESET_PASSWORD,
        PERMISSIONS.CONFIRM_PHONE_NUMBER,
    ]],

    [ROLES.CONFIRMED_EMAIL_AND_PHONE_TRANSPORTER, [
        PERMISSIONS.AUTHORIZATION,
        PERMISSIONS.RESET_PASSWORD,
        PERMISSIONS.FINISH_REGISTRATION,

    ]],
    [ROLES.CONFIRMED_EMAIL_AND_PHONE_HOLDER, [
        PERMISSIONS.AUTHORIZATION,
        PERMISSIONS.RESET_PASSWORD,
        PERMISSIONS.FINISH_REGISTRATION,

    ]],
    [ROLES.CONFIRMED_EMAIL_AND_PHONE_FORWARDER, [
        PERMISSIONS.AUTHORIZATION,
        PERMISSIONS.RESET_PASSWORD,
        PERMISSIONS.FINISH_REGISTRATION,
    ]],

    [ROLES.TRANSPORTER, [
        PERMISSIONS.AUTHORIZATION,
        PERMISSIONS.RESET_PASSWORD,
    ]],
    [ROLES.HOLDER, [
        PERMISSIONS.AUTHORIZATION,
        PERMISSIONS.RESET_PASSWORD,
    ]],
    [ROLES.FORWARDER, [
        PERMISSIONS.AUTHORIZATION,
        PERMISSIONS.RESET_PASSWORD,
    ]],
];

const FILE_LABELS = {
    PASSPORT: 'passport',
    PLAN: 'plan',
    REPORT: 'report',
};

module.exports = {
    ROLES,
    ROLES_TO_REGISTER,
    PERMISSIONS,
    ROLES_WITH_PERMISSIONS,
    MAP_ROLES_FROM_CLIENT_TO_SERVER,
    MAP_FROM_UNCONFIRMED_TO_CONFIRMED_EMAIL_ROLE,
    MAP_FROM_CONFIRMED_EMAIL_TO_CONFIRMED_PHONE,
    MAP_FROM_PENDING_ROLE_TO_MAIN,
    UNCONFIRMED_EMAIL_ROLES,
    FILE_LABELS,
};
